version: '3.8'
services:
  server_hello:
    image: tigase/tigase-xmpp-server:8.0.0
    ports:
      - "8480:8080"
      - "5422:5222"
    environment:
      - DB_ROOT_USER=admin
      - DB_ROOT_PASS=admin
      - ADMIN_JID=admin@server_hello 
      - ADMIN_PASSWORD=admin
    volumes:
      - ./tigase/config/tigase.conf:/home/tigase/tigase-server/etc/tigase.conf
      - ./tigase/config/config.tdsl:/home/tigase/tigase-server/etc/config.tdsl



# server_hello:
        #build:
    #  context: ./
    #  dockerfile: alpine.multiarch.Dockerfile
#    image: prosody/prosody:latest
#    ports:
#      - 5222:5222

  spade_hello:
    image: spade_hello:latest
    deploy:
      resources:
#        limits:
#          cpus: '0.5'
#          memory: 100M
#        reservations:
#          cpus: '0.25'
#          memory: 75M
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
